// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: futsal.proto

package data.proto;

public final class FutsalOuterClass {
  private FutsalOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_proto_GameNotification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_proto_GameNotification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_proto_None_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_proto_None_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014futsal.proto\022\ndata.proto\"2\n\020GameNotifi" +
      "cation\022\014\n\004date\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\"\006" +
      "\n\004None2D\n\006Futsal\022:\n\006notify\022\034.data.proto." +
      "GameNotification\032\020.data.proto.None\"\000B\002P\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_proto_GameNotification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_proto_GameNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_proto_GameNotification_descriptor,
        new java.lang.String[] { "Date", "Location", });
    internal_static_data_proto_None_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_proto_None_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_proto_None_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
