// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: futsal.proto

package data.proto;

public interface GameNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.proto.GameNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
