// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: futsal.proto

package data.proto;

public interface NoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.proto.None)
    com.google.protobuf.MessageOrBuilder {
}
